fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat'
    vcsrepo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
    openssl: 'git://github.com/camptocamp/puppet-openssl'
  symlinks:
    'acme': "#{source_dir}"
