fixtures:
  forge_modules:
    augeas_core: "puppetlabs/augeas_core"
    concat: "puppetlabs/concat"
    openssl: "puppet/openssl"
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
  symlinks:
    'acme': "#{source_dir}"
